#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 3.19.1-{branch}-{build}

branches:
  only:
    - master

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

build:
  parallel: true
  project: XOutput.sln
  include_nuget_references: true
  # MSBuild verbosity level - quiet|minimal|normal|detailed
  verbosity: normal 
  
before_build:
  - nuget restore
  
after_build:
  - 7z a XOutput.zip %APPVEYOR_BUILD_FOLDER%\XOutput\bin\Release\XOutput.exe

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: XOutput.zip
    name: XOutput

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

#---------------------------------#
#        global handlers          #
#---------------------------------#

on_success:

on_failure:

on_finish:


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Email
    to:
      - csutorasa@gmail.com
    on_build_success: false